// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abtflxgmjclxszrzaydz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidGZseGdtamNseHN6cnpheWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTU1OTEsImV4cCI6MjA3MTg3MTU5MX0.VqQoKenb5M13yvVwjXAY_AX1_OeG-HLQHrKSWPy5h7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});